/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './form-popup';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-params';
import * as import9 from 'ionic-angular/navigation/view-controller';
import * as import10 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import16 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/components/app/app';
import * as import23 from 'ionic-angular/navigation/nav-controller';
import * as import24 from 'ionic-angular/components/toolbar/toolbar';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import29 from 'ionic-angular/components/icon/icon';
import * as import30 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import31 from 'ionic-angular/components/navbar/navbar';
import * as import32 from 'ionic-angular/components/content/content';
import * as import33 from '@angular/core/src/security';
export class Wrapper_FormPopup {
  context:import0.FormPopup;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.FormPopup(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_FormPopup_Host:import2.RenderComponentType = (null as any);
class _View_FormPopup_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _FormPopup_0_4:Wrapper_FormPopup;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_FormPopup_Host0,renderType_FormPopup_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-form-popup',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FormPopup0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FormPopup_0_4 = new Wrapper_FormPopup(this.parentInjector.get(import8.NavParams),this.parentInjector.get(import9.ViewController),this.parentInjector.get(import10.DomSanitizer));
    this._appEl_0.initComponent(this._FormPopup_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._FormPopup_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FormPopup) && (0 === requestNodeIndex))) { return this._FormPopup_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FormPopup_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FormPopup_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_FormPopup_Host === (null as any))) { (renderType_FormPopup_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_FormPopup_Host0(viewUtils,parentInjector,declarationEl);
}
export const FormPopupNgFactory:import12.ComponentFactory<import0.FormPopup> = new import12.ComponentFactory<import0.FormPopup>('page-form-popup',viewFactory_FormPopup_Host0,import0.FormPopup);
const styles_FormPopup:any[] = ([] as any[]);
var renderType_FormPopup:import2.RenderComponentType = (null as any);
class _View_FormPopup0 extends import1.AppView<import0.FormPopup> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import15.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import16.Wrapper_ToolbarItem;
  _query_Button_7_0:import17.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _Icon_11_3:import18.Wrapper_Icon;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Content_17_4:import19.Wrapper_Content;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_FormPopup0,renderType_FormPopup,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import9.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import22.App),this.parentInjector.get(import9.ViewController,(null as any)),this.parentInjector.get(import23.NavController,(null as any)),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import15.Wrapper_ToolbarTitle(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import24.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import24.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_7_0 = new import17.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        Close\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','close-circle');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import18.Wrapper_Icon(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_7]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','form-popup');
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import19.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import19.Wrapper_Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import22.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import9.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'iframe',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','enketo-iframe');
    this.renderer.setElementAttribute(this._el_19,'id','form-iframe');
    this._text_20 = this.renderer.createText((null as any),'\n',(null as any));
    compView_17.create(this._Content_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_20
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import29.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3.context; }
    if (((token === import30.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarItem_7_3.context; }
    if (((token === import31.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4.context; }
    if (((token === import24.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_0_3.context; }
    if (((token === import32.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Content_17_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ToolbarItem_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_4:any = 'close-circle';
    this._Icon_11_3.check_name(currVal_4,throwOnChange,false);
    this._Icon_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Content_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_Button_7_0.dirty) {
      this._query_Button_7_0.reset(([] as any[]));
      this._ToolbarItem_7_3.context._buttons = this._query_Button_7_0;
      this._query_Button_7_0.notifyOnChanges();
    } }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n      ',this.context.form.title,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_5,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Icon_11_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._Content_17_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.enketoLink;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_19,'src',this.viewUtils.sanitizer.sanitize(import33.SecurityContext.RESOURCE_URL,currVal_7));
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_11_3.context.ngOnDestroy();
    this._Content_17_4.context.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FormPopup0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.FormPopup> {
  if ((renderType_FormPopup === (null as any))) { (renderType_FormPopup = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_FormPopup,{})); }
  return new _View_FormPopup0(viewUtils,parentInjector,declarationEl);
}