/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './record-data';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../providers/kobo-api';
import * as import5 from '@ionic/storage/es2015/storage';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/components/modal/modal';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '@angular/common/src/pipes/date_pipe';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from '@angular/core/src/linker/template_ref';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from '@angular/core/src/i18n/tokens';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import38 from '@angular/common/src/directives/ng_if';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from '@angular/common/src/directives/ng_for';
import * as import42 from 'ionic-angular/components/list/list';
import * as import43 from 'ionic-angular/components/content/content';
import * as import44 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import45 from 'ionic-angular/components/icon/icon';
import * as import46 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import47 from 'ionic-angular/util/form';
import * as import48 from 'ionic-angular/components/item/item-reorder';
import * as import49 from 'ionic-angular/components/item/item';
export class Wrapper_RecordDataPage {
  context:import0.RecordDataPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.RecordDataPage(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_RecordDataPage_Host:import2.RenderComponentType = (null as any);
class _View_RecordDataPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _KoboApi_0_4:import4.KoboApi;
  _Storage_0_5:import5.Storage;
  _RecordDataPage_0_6:Wrapper_RecordDataPage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage_Host0,renderType_RecordDataPage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-record-data',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RecordDataPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._KoboApi_0_4 = new import4.KoboApi(this.parentInjector.get(import10.Http));
    this._Storage_0_5 = new import5.Storage();
    this._RecordDataPage_0_6 = new Wrapper_RecordDataPage(this._KoboApi_0_4,this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.ModalController),this._Storage_0_5);
    this._appEl_0.initComponent(this._RecordDataPage_0_6.context,([] as any[]),compView_0);
    compView_0.create(this._RecordDataPage_0_6.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.KoboApi) && (0 === requestNodeIndex))) { return this._KoboApi_0_4; }
    if (((token === import5.Storage) && (0 === requestNodeIndex))) { return this._Storage_0_5; }
    if (((token === import0.RecordDataPage) && (0 === requestNodeIndex))) { return this._RecordDataPage_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RecordDataPage_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RecordDataPage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RecordDataPage_Host === (null as any))) { (renderType_RecordDataPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RecordDataPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RecordDataPageNgFactory:import14.ComponentFactory<import0.RecordDataPage> = new import14.ComponentFactory<import0.RecordDataPage>('page-record-data',viewFactory_RecordDataPage_Host0,import0.RecordDataPage);
const styles_RecordDataPage:any[] = ([] as any[]);
var renderType_RecordDataPage:import2.RenderComponentType = (null as any);
class _View_RecordDataPage0 extends import1.AppView<import0.RecordDataPage> {
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import17.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import18.Wrapper_ToolbarItem;
  _query_Button_7_0:import19.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import20.Wrapper_NgIf;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import20.Wrapper_NgIf;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import20.Wrapper_NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import20.Wrapper_NgIf;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Content_23_4:import21.Wrapper_Content;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _List_28_3:import22.Wrapper_List;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _TemplateRef_30_5:any;
  _NgFor_30_6:import23.Wrapper_NgFor;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_7:any;
  _pipe_date_0:import24.DatePipe;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage0,renderType_RecordDataPage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Record Data',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import18.Wrapper_ToolbarItem(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_7_0 = new import19.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_11 = new import3.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import30.TemplateRef_(this._appEl_11,viewFactory_RecordDataPage1);
    this._NgIf_11_6 = new import20.Wrapper_NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_13 = new import3.AppElement(13,9,this,this._anchor_13);
    this._TemplateRef_13_5 = new import30.TemplateRef_(this._appEl_13,viewFactory_RecordDataPage2);
    this._NgIf_13_6 = new import20.Wrapper_NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_15 = new import3.AppElement(15,9,this,this._anchor_15);
    this._TemplateRef_15_5 = new import30.TemplateRef_(this._appEl_15,viewFactory_RecordDataPage3);
    this._NgIf_15_6 = new import20.Wrapper_NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_17 = new import3.AppElement(17,9,this,this._anchor_17);
    this._TemplateRef_17_5 = new import30.TemplateRef_(this._appEl_17,viewFactory_RecordDataPage4);
    this._NgIf_17_6 = new import20.Wrapper_NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_19 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_7]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_20
      ]
      )
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_23 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','forms-overview');
    this.renderer.setElementAttribute(this._el_23,'padding','');
    this._appEl_23 = new import3.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import21.viewFactory_Content0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Content_23_4 = new import21.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_23.initComponent(this._Content_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Available Forms',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_28_3 = new import22.Wrapper_List(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import34.GestureController));
    this._text_29 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._appEl_30 = new import3.AppElement(30,28,this,this._anchor_30);
    this._TemplateRef_30_5 = new import30.TemplateRef_(this._appEl_30,viewFactory_RecordDataPage5);
    this._NgFor_30_6 = new import23.Wrapper_NgFor(this._appEl_30.vcRef,this._TemplateRef_30_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_31 = this.renderer.createText(this._el_28,'\n  ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'id','info');
    this._text_34 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'h3',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Info',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_33,'p',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'If you have internet the app will attempt to contact the kobo server and return forms from a demo account.',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_33,'p',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Once downloaded, links will be generated to complete the form using Enketo. Once the form has been opened once it is cached to work without internet.',(null as any));
    this._text_43 = this.renderer.createText(this._el_33,'\n  ',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_23.create(this._Content_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._el_25,
        this._text_27,
        this._el_28,
        this._text_32,
        this._el_33,
        this._text_44
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_7 = import9.UNINITIALIZED;
    this._pipe_date_0 = new import24.DatePipe(this.parentInjector.get(import36.LOCALE_ID));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import30.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import38.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import30.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import38.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import30.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import38.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import30.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import38.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    if (((token === import39.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ToolbarItem_7_3.context; }
    if (((token === import40.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Navbar_2_4.context; }
    if (((token === import29.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Header_0_3.context; }
    if (((token === import30.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import41.NgFor) && (30 === requestNodeIndex))) { return this._NgFor_30_6.context; }
    if (((token === import42.List) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._List_28_3.context; }
    if (((token === import43.Content) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Content_23_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ToolbarItem_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_3:boolean = !this.context.finished;
    this._NgIf_11_6.check_ngIf(currVal_3,throwOnChange,false);
    this._NgIf_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    const currVal_4:any = this.context.anyErrors;
    this._NgIf_13_6.check_ngIf(currVal_4,throwOnChange,false);
    this._NgIf_13_6.detectChangesInternal(this,this._anchor_13,throwOnChange);
    const currVal_5:any = (this.context.finished && !this.context.anyErrors);
    this._NgIf_15_6.check_ngIf(currVal_5,throwOnChange,false);
    this._NgIf_15_6.detectChangesInternal(this,this._anchor_15,throwOnChange);
    const currVal_6:any = (this.context.finished || this.context.anyErrors);
    this._NgIf_17_6.check_ngIf(currVal_6,throwOnChange,false);
    this._NgIf_17_6.detectChangesInternal(this,this._anchor_17,throwOnChange);
    if (this._Content_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._List_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_8:any = this.context.forms;
    this._NgFor_30_6.check_ngForOf(currVal_8,throwOnChange,false);
    this._NgFor_30_6.detectChangesInternal(this,this._anchor_30,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_Button_7_0.dirty) {
      this._query_Button_7_0.reset(([] as any[]));
      this._ToolbarItem_7_3.context._buttons = this._query_Button_7_0;
      this._query_Button_7_0.notifyOnChanges();
    } }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_7:any = this._Content_23_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_23,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_23_4.context.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.refresh()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RecordDataPage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RecordDataPage> {
  if ((renderType_RecordDataPage === (null as any))) { (renderType_RecordDataPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_RecordDataPage,{})); }
  return new _View_RecordDataPage0(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage1,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Refreshing forms...',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_RecordDataPage1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage1(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage2,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Error',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_RecordDataPage2(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage2(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage3,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Refresh',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_RecordDataPage3(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage3(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage4 extends import1.AppView<any> {
  _el_0:any;
  _Icon_0_3:import44.Wrapper_Icon;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage4,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'name','refresh');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import44.Wrapper_Icon(this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'refresh';
    this._Icon_0_3.check_name(currVal_0,throwOnChange,false);
    this._Icon_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Icon_0_3.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_0_3.context.ngOnDestroy();
  }
}
function viewFactory_RecordDataPage4(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage4(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import46.Wrapper_Item;
  _ItemContent_0_5:import46.Wrapper_ItemContent;
  _query_Label_0_0:import19.QueryList<any>;
  _query_Button_0_1:import19.QueryList<any>;
  _query_Icon_0_2:import19.QueryList<any>;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import20.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import20.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import20.Wrapper_NgIf;
  _text_13:any;
  /*private*/ _expr_2:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage5,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import46.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import46.Wrapper_Item(this.parent.parentInjector.get(import47.Form),this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import48.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import46.Wrapper_ItemContent();
    this._query_Label_0_0 = new import19.QueryList<any>();
    this._query_Button_0_1 = new import19.QueryList<any>();
    this._query_Icon_0_2 = new import19.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import30.TemplateRef_(this._appEl_2,viewFactory_RecordDataPage6);
    this._NgIf_2_6 = new import20.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import3.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import30.TemplateRef_(this._appEl_4,viewFactory_RecordDataPage7);
    this._NgIf_4_6 = new import20.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_12 = new import3.AppElement(12,0,this,this._anchor_12);
    this._TemplateRef_12_5 = new import30.TemplateRef_(this._appEl_12,viewFactory_RecordDataPage8);
    this._NgIf_12_6 = new import20.Wrapper_NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([
        this._appEl_2,
        this._appEl_4
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3,
        this._text_5,
        this._el_6,
        this._text_8,
        this._el_9,
        this._text_11,
        this._text_13
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._appEl_12])
    ]
    ,(null as any));
    this._expr_2 = import9.UNINITIALIZED;
    this._pipe_date_0_0 = import6.pureProxy2((<_View_RecordDataPage0>this.parent)._pipe_date_0.transform.bind((<_View_RecordDataPage0>this.parent)._pipe_date_0));
    this._expr_3 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._anchor_12,
      this._text_13
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import38.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import30.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import38.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import30.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import38.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import49.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_0_4.context; }
    if (((token === import49.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import9.ValueUnwrapper();
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = this.context.$implicit.downloadable;
    this._NgIf_2_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    const currVal_1:boolean = !this.context.$implicit.downloadable;
    this._NgIf_4_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    const currVal_4:any = (this.context.$implicit.enketoLink && this.context.$implicit.downloadable);
    this._NgIf_12_6.check_ngIf(currVal_4,throwOnChange,false);
    this._NgIf_12_6.detectChangesInternal(this,this._anchor_12,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([
          this._appEl_2.mapNestedViews(_View_RecordDataPage6,(nestedView:_View_RecordDataPage6):any => {
            return [nestedView._Icon_0_3.context];
          }),
          this._appEl_4.mapNestedViews(_View_RecordDataPage7,(nestedView:_View_RecordDataPage7):any => {
            return [nestedView._Icon_0_3.context];
          }),
          this._appEl_12.mapNestedViews(_View_RecordDataPage8,(nestedView:_View_RecordDataPage8):any => {
            return [nestedView._Icon_2_3.context];
          })
        ]
        );
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.title,'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_7,currVal_2);
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import6.interpolate(1,'',valUnwrapper.unwrap(import6.castByValue(this._pipe_date_0_0,(<_View_RecordDataPage0>this.parent)._pipe_date_0.transform)(this.context.$implicit.date_modified,'medium')),'');
    if ((valUnwrapper.hasWrappedValue || import6.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_10,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RecordDataPage5(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage5(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage6 extends import1.AppView<any> {
  _el_0:any;
  _Icon_0_3:import44.Wrapper_Icon;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage6,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-left','');
    this.renderer.setElementAttribute(this._el_0,'name','clipboard');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import44.Wrapper_Icon(this.parent.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'clipboard';
    this._Icon_0_3.check_name(currVal_0,throwOnChange,false);
    this._Icon_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Icon_0_3.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_RecordDataPage5>this.parent)._query_Icon_0_2.setDirty();
  }
  destroyInternal():void {
    this._Icon_0_3.context.ngOnDestroy();
  }
}
function viewFactory_RecordDataPage6(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage6(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage7 extends import1.AppView<any> {
  _el_0:any;
  _Icon_0_3:import44.Wrapper_Icon;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage7,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-left','');
    this.renderer.setElementAttribute(this._el_0,'light-grey','');
    this.renderer.setElementAttribute(this._el_0,'name','clipboard');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import44.Wrapper_Icon(this.parent.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'clipboard';
    this._Icon_0_3.check_name(currVal_0,throwOnChange,false);
    this._Icon_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Icon_0_3.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_RecordDataPage5>this.parent)._query_Icon_0_2.setDirty();
  }
  destroyInternal():void {
    this._Icon_0_3.context.ngOnDestroy();
  }
}
function viewFactory_RecordDataPage7(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage7(viewUtils,parentInjector,declarationEl);
}
class _View_RecordDataPage8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import44.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_RecordDataPage8,renderType_RecordDataPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'clear','');
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','open');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import44.Wrapper_Icon(this.parent.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_0,'\n        Open Form\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'open';
    this._Icon_2_3.check_name(currVal_1,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_2_3.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_RecordDataPage5>this.parent)._query_Icon_0_2.setDirty();
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.openForm(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_RecordDataPage8(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RecordDataPage8(viewUtils,parentInjector,declarationEl);
}